name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn --frozen-lockfile
      - run: yarn run lint
      - run: yarn format_check
      - run: CI=true yarn test
      - name: Publish Production
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && github.repository == 'antipycorp/deno_website2'
        uses: cloudflare/wrangler-action@1.1.0
        with:
          environment: 'production'
          apiToken: ${{ secrets.cloudflareToken }}
          workingDirectory: worker
      - name: Publish Staging
        if: github.event_name == 'push' && github.repository == 'antipycorp/deno_website2'
        uses: cloudflare/wrangler-action@1.1.0
        with:
          environment: 'staging'
          apiToken: ${{ secrets.cloudflareToken }}
          workingDirectory: worker
